// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// File ini identik dengan yang ada di service-a.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

type MedicalRecordServiceClient interface {
	CheckPatientRecord(ctx context.Context, in *PatientRequest, opts ...grpc.CallOption) (*RecordResponse, error)
}

type medicalRecordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMedicalRecordServiceClient(cc grpc.ClientConnInterface) MedicalRecordServiceClient {
	return &medicalRecordServiceClient{cc}
}

func (c *medicalRecordServiceClient) CheckPatientRecord(ctx context.Context, in *PatientRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, "/medicalrecord.MedicalRecordService/CheckPatientRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type MedicalRecordServiceServer interface {
	CheckPatientRecord(context.Context, *PatientRequest) (*RecordResponse, error)
	GetAllRecords(context.Context, *GetRecordsRequest) (*RecordsListResponse, error)
	mustEmbedUnimplementedMedicalRecordServiceServer()
}

type UnimplementedMedicalRecordServiceServer struct{}

func (UnimplementedMedicalRecordServiceServer) CheckPatientRecord(context.Context, *PatientRequest) (*RecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPatientRecord not implemented")
}

func (UnimplementedMedicalRecordServiceServer) GetAllRecords(context.Context, *GetRecordsRequest) (*RecordsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRecords not implemented")
}

func (UnimplementedMedicalRecordServiceServer) mustEmbedUnimplementedMedicalRecordServiceServer() {}

type UnsafeMedicalRecordServiceServer interface {
	mustEmbedUnimplementedMedicalRecordServiceServer()
}

func RegisterMedicalRecordServiceServer(s grpc.ServiceRegistrar, srv MedicalRecordServiceServer) {
	s.RegisterService(&MedicalRecordService_ServiceDesc, srv)
}

func _MedicalRecordService_CheckPatientRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedicalRecordServiceServer).CheckPatientRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/medicalrecord.MedicalRecordService/CheckPatientRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedicalRecordServiceServer).CheckPatientRecord(ctx, req.(*PatientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedicalRecordService_GetAllRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedicalRecordServiceServer).GetAllRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/medicalrecord.MedicalRecordService/GetAllRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedicalRecordServiceServer).GetAllRecords(ctx, req.(*GetRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var MedicalRecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medicalrecord.MedicalRecordService",
	HandlerType: (*MedicalRecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPatientRecord",
			Handler:    _MedicalRecordService_CheckPatientRecord_Handler,
		},
		{
			MethodName: "GetAllRecords",
			Handler:    _MedicalRecordService_GetAllRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "medical_record.proto",
}
