// Code generated by protoc-gen-go. DO NOT EDIT.
// Versi manual — untuk keperluan tugas.
// Dalam proyek nyata, generate dengan: protoc --go_out=. --go-grpc_out=. medical_record.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

type PatientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	Nik           string `protobuf:"bytes,1,opt,name=nik,proto3" json:"nik,omitempty"`
}

func (x *PatientRequest) Reset()         { *x = PatientRequest{} }
func (x *PatientRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *PatientRequest) ProtoMessage()  {}

func (x *PatientRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *PatientRequest) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	HasRecord     bool   `protobuf:"varint,1,opt,name=has_record,json=hasRecord,proto3" json:"has_record,omitempty"`
	RecordId      string `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RecordResponse) Reset()         { *x = RecordResponse{} }
func (x *RecordResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *RecordResponse) ProtoMessage()  {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *RecordResponse) GetHasRecord() bool {
	if x != nil {
		return x.HasRecord
	}
	return false
}

func (x *RecordResponse) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *RecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var _ = sync.Once{}
var _ = reflect.TypeOf
